title: Shrihith Anantharam
description: "| Bioinformatician | Microbiologist | | Python Developer |"
site_title: '@Shrihith - Shrihith Anantharam'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: Shrihith
blog_url: https://shrihith93.blogspot.com
email: shrihith93@gmail.com
keybase_username: shrihith93
twitter_username: shrihith93
reddit_username: abhn

# absolute or relative
profile_picture: assets/images/shrihith.png

# Google Analytics ID
google_analytics: G-4B49RG4CR4